// <auto-generated />
namespace JobBoard.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class migrationss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationss));
        
        string IMigrationMetadata.Id
        {
            get { return "201405022103018_migrationss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
